### ISSUE TITLE
Tracking Work Week 6

### ISSUE THREAD

**Issue by LengTech11** [LengTech11/ML-Flutter-Disease-detector-APP#65]
### Admin Dashboard  (Sambo)

- [X]  UI
- [X] Manage User
- [x] Diseases management
- [x] Manage Document 
      - import and rename document

### Flutter (Sambath)
- [X]  Auth UI
- [X] Splash Screen
- [X] User Profile
- [X] Splash Screen
- [x]  Call API Auth
- [x] Call API Predict (Flask API)
- [x] Call API History
- [x] Call API Document

### Flutter (Sokleng)
- [X] UI Onboarding screen
- [X] Home or Upload Screen
- [X] Eyes disease and History Screen
- [X] Profile Screen
- [x]  ButtonSheet detail Diseases 

### API (Sokleng)
- [x] Laravel API User 
- [x] Laravel API Document
- [x] Laravel API Disease Description
- [x] Laravel User History Prediction
- [x] Flask API Prediction
